insert into conceptos (id, nombre, valor, tipo) values (214,'INACTIVO', 'Inactivo', 'estado');
insert into conceptos (id, nombre, valor, tipo) values (215,'EN_OBRA', 'En Obra', 'estado');
insert into conceptos (id, nombre, valor, tipo) values (216,'ACTIVO', 'Activo', 'estado');
insert into conceptos (id, nombre, valor, tipo) values (217,'PLANIF', 'Planificado', 'estado_planif');
insert into conceptos (id, nombre, valor, tipo) values (218,'NO_PLANIF', 'No Planificado', 'estado_planif');
insert into conceptos (id, nombre, valor, tipo) values (219,'SECTOR_1', 'Sector 1', 'sectorizacion');
insert into conceptos (id, nombre, valor, tipo) values (220,'SECTOR_2', 'Sector 2', 'sectorizacion');
insert into conceptos (id, nombre, valor, tipo) values (221,'SECTOR_3', 'Sector 3', 'sectorizacion');
insert into conceptos (id, nombre, valor, tipo) values (222,'SECTOR_4', 'Sector 4', 'sectorizacion');
insert into conceptos (id, nombre, valor, tipo) values (223,'SECTOR_5', 'Sector 5', 'sectorizacion');
insert into conceptos (id, nombre, valor, tipo) values (224,'SECTOR_6', 'Sector 6', 'sectorizacion');
insert into conceptos (id, nombre, valor, tipo) values (225,'2G', '2G', 'tecnologias_4g');
insert into conceptos (id, nombre, valor, tipo) values (226,'3G', '3G', 'tecnologias_4g');
insert into conceptos (id, nombre, valor, tipo) values (227,'4G', '4G', 'tecnologias_4g');
insert into conceptos (id, nombre, valor, tipo) values (228,'FO', 'Fibra Óptica', 'tipo_acc_4g');
insert into conceptos (id, nombre, valor, tipo) values (229,'RADIOENLACE', 'Radioenlace', 'tipo_acc_4g');
insert into conceptos (id, nombre, valor, tipo) values (230,'WIMAX', 'WiMax', 'tipo_acc_4g');
insert into conceptos (id, nombre, valor, tipo) values (231,'LTE', 'LTE', 'tipo_acc_4g');
insert into conceptos (id, nombre, valor, tipo) values (232,'OTRO', 'Otro', 'tipo_acc_4g');
insert into conceptos (id, nombre, valor, tipo) values (233,'SI', 'SI', 'booleano');
insert into conceptos (id, nombre, valor, tipo) values (234,'NO', 'NO', 'booleano');
insert into conceptos (id, nombre, valor, tipo) values (235,'ETAPA_1', 'Etapa 1', 'etapa');
insert into conceptos (id, nombre, valor, tipo) values (236,'ETAPA_2', 'Etapa 2', 'etapa');
insert into conceptos (id, nombre, valor, tipo) values (237,'ETAPA_3', 'Etapa 3', 'etapa');
insert into conceptos (id, nombre, valor, tipo) values (238,'ETAPA_4', 'Etapa 4', 'etapa');
insert into conceptos (id, nombre, valor, tipo) values (239,'ETAPA_5', 'Etapa 5', 'etapa');
insert into conceptos (id, nombre, valor, tipo) values (240,'703_NAC_SCMA', '703- NACIONAL- SCMA - MOVISTAR', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (241,'713_NAC_SCMA', '713- NACIONAL- SCMA - PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (242,'723_NAC_SCMA', '723- NACIONAL- SCMA - CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (243,'738_NAC_SCMA', '738- NACIONAL- SCMA- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (244,'758_NAC_SCMA', '758- NACIONAL- SCMA - MOVISTAR', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (245,'768_NAC_SCMA', '768- NACIONAL- SCMA- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (246,'778_NAC_SCMA', '778- NACIONAL- SCMA - CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (247,'793_NAC_SCMA', '793- NACIONAL- SCMA- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (248,'830.25_AREA2_SRMC', '830.25- AREA2- SRMC- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (249,'875.25_AREA2_SRMC', '875.25- AREA2- SRMC- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (250,'1710_NAC_SCMA', '1710- NACIONAL- SCMA- MOVISTAR', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (251,'1720_NAC_SCMA', '1720- NACIONAL- SCMA- CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (252,'1730_NAC_SCMA', '1730- NACIONAL- SCMA- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (253,'1745_NAC_SCMA', '1745- NACIONAL- SCMA- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (254,'1862.5_AREA3_PCS', '1862.5- AREA3- PCS- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (255,'1867.5_AREA3_PCS', '1867.5- AREA3- PCS- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (256,'1870_AREA2_PCS', '1870- AREA2- PCS- CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (257,'1880_AREA3_PCS', '1880- AREA3- PCS- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (258,'1890_AREA2_PCS', '1890- AREA2- PCS- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (259,'1890_AREA1_PCS', '1890- AREA1- PCS- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (260,'1892.5_AREA1_PCS', '1892.5- AREA1- PCS- CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (261,'1895_AREA1_PCS', '1895- AREA1- PCS- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (262,'1942.5_AREA3_PCS', '1942.5- AREA3- PCS- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (263,'1947.5_AREA3_PCS', '1947.5- AREA3- PCS- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (264,'1950_AREA2_PCS', '1950- AREA2- PCS- CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (265,'1960_AREA3_PCS', '1960- AREA3- PCS- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (266,'1970_AREA2_PCS', '1970- AREA2- PCS- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (267,'1970_AREA1_PCS', '1970- AREA1- PCS- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (268,'1972.5_AREA1_PCS', '1972.5- AREA1- PCS- CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (269,'1975_AREA1_PCS', '1975- AREA1- PCS- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (270,'2110_NAC_SCMA', '2110- NACIONAL- SCMA- MOVISTAR', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (271,'2120_NAC_SCMA', '2120- NACIONAL- SCMA- CLARO', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (272,'2130_NAC_SCMA', '2130- NACIONAL- SCMA- PERSONAL', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (273,'2145_NAC_SCMA', '2145- NACIONAL- SCMA- ARLINK SA', '4G_BANDAS');
insert into conceptos (id, nombre, valor, tipo) values (274,'CONV', 'Convencional', '4G_TIPO_SITIO');
insert into conceptos (id, nombre, valor, tipo) values (275,'INDOOR', 'Indoor', '4G_TIPO_SITIO');
insert into conceptos (id, nombre, valor, tipo) values (276,'DISTRIB', 'Distribuido', '4G_TIPO_SITIO');
insert into conceptos (id, nombre, valor, tipo) values (277,'CAMUF', 'Camuflado', '4G_TIPO_SITIO');
insert into conceptos (id, nombre, valor, tipo) values (278,'OTRO', 'Otros', '4G_TIPO_SITIO');